name: fap_helper_v1
description: "Ứng dụng quản lý lớp và lịch dạy FA26 dành cho giảng viên."
publish_to: 'none'
version: 0.3.3+6

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  xml: ^6.6.1
  qr_flutter: ^4.1.0
  jose: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/student/
